"""Initial migration

Revision ID: 717fdaf6223e
Revises: 
Create Date: 2025-02-11 14:54:43.682483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717fdaf6223e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('title')
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
